# Análise Exploratória de Dados (EDA)

## 1. Introdução

Este projeto realiza uma Análise Exploratória de Dados (EDA) sobre corridas da Uber com o objetivo de compreender padrões de utilização, comportamento temporal das corridas e possíveis aplicações de modelos de Inteligência Artificial para previsão de demanda.

**Objetivo da análise:**

- entender padrões de uso da Uber

- analisar variáveis do dataset

- identificar padrões temporais

- verificação o que leva uma pessoa cancelar uma corrida 

- gerar visualizações

- indicar possíveis aplicações de IA

In [2]:
!pip install missingno

Collecting missingno
  Downloading missingno-0.5.2-py3-none-any.whl.metadata (639 bytes)
Requirement already satisfied: numpy in c:\users\graci.desktop-i7t8uk6\anaconda3\lib\site-packages (from missingno) (2.3.5)
Requirement already satisfied: matplotlib in c:\users\graci.desktop-i7t8uk6\anaconda3\lib\site-packages (from missingno) (3.10.6)
Requirement already satisfied: scipy in c:\users\graci.desktop-i7t8uk6\anaconda3\lib\site-packages (from missingno) (1.16.3)
Requirement already satisfied: seaborn in c:\users\graci.desktop-i7t8uk6\anaconda3\lib\site-packages (from missingno) (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\graci.desktop-i7t8uk6\anaconda3\lib\site-packages (from matplotlib->missingno) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\graci.desktop-i7t8uk6\anaconda3\lib\site-packages (from matplotlib->missingno) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\graci.desktop-i7t8uk6\anaconda3\lib\site-packages (from matplotlib->missingno) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\graci.desktop-i7t8uk6\anaconda3\lib\site-packages (from matplotlib->missingno) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\graci.desktop-i7t8uk6\anaconda3\lib\site-packages (from matplotlib->missingno) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\graci.desktop-i7t8uk6\anaconda3\lib\site-packages (from matplotlib->missingno) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\graci.desktop-i7t8uk6\anaconda3\lib\site-packages (from matplotlib->missingno) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\graci.desktop-i7t8uk6\anaconda3\lib\site-packages (from matplotlib->missingno) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\graci.desktop-i7t8uk6\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib->missingno) (1.17.0)
Requirement already satisfied: pandas>=1.2 in c:\users\graci.desktop-i7t8uk6\anaconda3\lib\site-packages (from seaborn->missingno) (2.3.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\graci.desktop-i7t8uk6\anaconda3\lib\site-packages (from pandas>=1.2->seaborn->missingno) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\graci.desktop-i7t8uk6\anaconda3\lib\site-packages (from pandas>=1.2->seaborn->missingno) (2025.2)
Downloading missingno-0.5.2-py3-none-any.whl (8.7 kB)
Installing collected packages: missingno
Successfully installed missingno-0.5.2

## 2. Importação das bibliotecas

In [3]:
# importação das bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno
import warnings
import os

warnings.filterwarnings("ignore")
plt.style.use("ggplot")

## 3. Carregamento dos dados

In [4]:
df = pd.read_csv("../data/raw/ncr_ride_bookings.csv")

In [5]:
df.shape

(150000, 21)

In [6]:
df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI

## 4. Entendimento inicial dos dados

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 21 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               150000 non-null  object
 1   Time                               150000 non-null  object
 2   Booking ID                         150000 non-null  object
 3   Booking Status                     150000 non-null  object
 4   Customer ID                        150000 non-null  object
 5   Vehicle Type                       150000 non-null  object
 6   Pickup Location                    150000 non-null  object
 7   Drop Location                      150000 non-null  object
 8   Avg VTAT                           139500 non-null  float64
 9   Avg CTAT                           102000 non-null  float64
 10  Cancelled Rides by Customer        10500 non-null   float64
 11  Reason for cancelling by Customer  10500 non-null   object
 12  Cancelled Rides by Driver          27000 non-null   float64
 13  Driver Cancellation Reason         27000 non-null   object
 14  Incomplete Rides                   9000 non-null    float64
 15  Incomplete Rides Reason            9000 non-null    object
 16  Booking Value                      102000 non-null  float64
 17  Ride Distance                      102000 non-null  float64
 18  Driver Ratings                     93000 non-null   float64
 19  Customer Rating                    93000 non-null   float64
 20  Payment Method                     102000 non-null  object
dtypes: float64(9), object(12)
memory usage: 24.0+ MB

In [8]:
df.describe()

,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Cancelled Rides by Driver,Incomplete Rides,Booking Value,Ride Distance,Driver Ratings,Customer Rating
count,139500.000000,102000.000000,10500.0,27000.0,9000.0,102000.000000,102000.000000,93000.000000,93000.000000
mean,8.456352,29.149636,1.0,1.0,1.0,508.295912,24.637012,4.230992,4.404584
std,3.773564,8.902577,0.0,0.0,0.0,395.805774,14.002138,0.436871,0.437819
min,2.000000,10.000000,1.0,1.0,1.0,50.000000,1.000000,3.000000,3.000000
25%,5.300000,21.600000,1.0,1.0,1.0,234.000000,12.460000,4.100000,4.200000
50%,8.300000,28.800000,1.0,1.0,1.0,414.000000,23.720000,4.300000,4.500000
75%,11.300000,36.800000,1.0,1.0,1.0,689.000000,36.820000,4.600000,4.800000
max,20.000000,45.000000,1.0,1.0,1.0,4277.000000,50.000000,5.000000,5.000000

In [9]:
df.columns

Index(['Date', 'Time', 'Booking ID', 'Booking Status', 'Customer ID',
       'Vehicle Type', 'Pickup Location', 'Drop Location', 'Avg VTAT',
       'Avg CTAT', 'Cancelled Rides by Customer',
       'Reason for cancelling by Customer', 'Cancelled Rides by Driver',
       'Driver Cancellation Reason', 'Incomplete Rides',
       'Incomplete Rides Reason', 'Booking Value', 'Ride Distance',
       'Driver Ratings', 'Customer Rating', 'Payment Method'],
      dtype='object')

## 5. Dicionário dos dados

In [10]:
# Criação do dicionário de dados
data_dictionary = pd.DataFrame([
    {
        'varible': 'Date',
        'description': 'Date of the booking',
        'type': 'quantitative',
        'subtype': 'continua',
    },
    {
        'varible': 'Time',
        'description': 'Time of the booking',
        'type': 'quantitative',
        'subtype': 'continua',
    },
     {
        'varible': 'Booking ID',
        'description': 'Unique identifier for each ride booking',
        'type': 'quantitative',
        'subtype': 'continua',
    },
     {
        'varible': 'Booking Status',
        'description': 'Status of booking (Completed, Cancelled by Customer, Cancelled by Driver, etc.)',
        'type': 'quantitative',
        'subtype': 'continua',
    },
    {
        'varible': 'Customer ID',
        'description': 'Unique identifier for customers',
        'type': 'Quantitative',
        'subtype': 'continua',
    },
    {
        'varible': 'Vehicle Type',
        'description': 'Type of vehicle (Go Mini, Go Sedan, Auto, eBike/Bike, UberXL, Premier Sedan',
        'type': 'qualitative',
        'subtype': 'ordinal',
    },
    {
        'varible': 'Pickup Location',
        'description': 'Starting location of the ride',
        'type': 'quantitative',
        'subtype': 'continua',
    },
     {
        'varible': 'Drop Location',
        'description': 'Destination location of the ride',
        'type': 'quantitative',
        'subtype': 'continua',
    },
     {
        'varible': 'Avg VTAT',
        'description': 'Average time for driver to reach pickup location (in minutes)',
        'type': 'quantitative',
        'subtype': 'continua',
    },
    {
        'varible': 'Avg CTAT',
        'description': 'Average trip duration from pickup to destination (in minutes)',
        'type': 'quantitative',
        'subtype': 'continua',
    },
     {
        'varible': 'Cancelled Rides by Customer',
        'description': 'Customer-initiated cancellation flag',
        'type': 'quantitative',
        'subtype': 'continua',
    },
    {
        'varible': 'Reason for cancelling by Customer',
        'description': 'Reason for customer cancellation',
        'type': 'quantitative',
        'subtype': 'continua',
    },
     {
        'varible': 'Cancelled Rides by Driver',
        'description': 'Driver-initiated cancellation flag',
        'type': 'quantitative',
        'subtype': 'continua',
    },
    {
        'varible': 'Driver Cancellation Reason',
        'description': 'Reason for driver cancellation',
        'type': 'quantitative',
        'subtype': 'continua',
    },
    {
        'varible': 'Incomplete Rides',
        'description': 'Incomplete ride flag',
        'type': 'quantitative',
        'subtype': 'continua',
    },
    {
        'varible': 'Incomplete Rides Reason',
        'description': 'Reason for incomplete rides',
        'type': 'quantitative',
        'subtype': 'continua',
    },
    {
        'varible': 'Booking Value',
        'description': 'Total fare amount for the ride',
        'type': 'quantitative',
        'subtype': 'continua',
    },
    {
        'varible': 'Ride Distance',
        'description': 'Distance covered during the ride (in km)',
        'type': 'quantitative',
        'subtype': 'continua',
    },
    {
        'varible': 'Driver Ratings',
        'description': 'Rating given to driver (1-5 scale)',
        'type': 'quantitative',
        'subtype': 'continua',
    },
     {
        'varible': 'Customer Rating',
        'description': 'Rating given by customer (1-5 scale)',
        'type': 'quantitative',
        'subtype': 'continua',
    },
     {
        'varible': 'Payment Method',
        'description': 'Method used for payment (UPI, Cash, Credit Card, Uber Wallet, Debit Card)',
        'type': 'quantitative',
        'subtype': 'continua',
    },

_IncompleteInputError: incomplete input (79850529.py, line 8)